INSERT
INTO
    permissin_group
(
    DEFAULTGRP
,   AUTHGRPNAME
,   AUTHGRPNAMEID
,   UPDATEDAT
) VALUES
    (TRUE, '오퍼레이터', 'DAP_OPERATOR', CURRENT_TIMESTAMP)
,   (TRUE, '옵저버', 'DAP_OBSERVER', CURRENT_TIMESTAMP)
,   (TRUE, '자산관리자', 'DAP_MANAGER', CURRENT_TIMESTAMP)
,   (TRUE, '일반사용자', 'COMMON_USER', CURRENT_TIMESTAMP)
,   (TRUE, '일반가맹점', 'COMMON_FRANCHISEE', CURRENT_TIMESTAMP)
;