SELECT
    CONTRACTID
,   ARCHIVEDID
,   PARENTID
,   TEMPLATEID
,   SIGNATORIES
,   OBSERVERS
,   EXECISERCHOICE
,   UUID
,   STATUS
,   CONTRACTITEM
FROM
    CONTRACT
WHERE
    CONTRACTID  =   :#${headers.dsl[contractid]}
;