SELECT  ID
       ,PWDRULEMIN
       ,PWDRULEMAX
       ,PWDRULEPERIOD
       ,PWDRULEFAILNOTLOGIN
       ,PWDRULEFAILCNTLIMIT
       ,PWDRULEANYWHEREABLE
       ,PWDRULEINCNUM
       ,PWDRULEINCSPECIAL
       ,PWDRULEINCUPPER
       ,PWDRULEINCLOWER
       ,SSTIMEOUTABLE
       ,SSTIMEOUTMIN
       ,DAPCONSOID
       ,DAPPRIVACYGRPID
       ,CTRLIMITWON
       ,CREATEDAT
       ,UPDATEDAT
FROM POLICY
ORDER BY CREATEDAT DESC
LIMIT 1 ;